namespace: fitness-tracker

useSealedSecrets: false

app:
  database:
    engine: postgresql
    host: db.example.com
    name: fitness_tracker
    password: Sup3rS3cr3tP455w0rd
    port: "5432"
    username: fitness_tracker_user
  debug: "0"
  image:
    repository: ghcr.io/m5lapp/fitness-tracker
    tag: ""
  ports:
    internal: 8080
  probes:
    liveness:
      active: true
      path: /admin/
  replicas: 1
  resources:
    limits:
      # cpu: "500m"
      memory: "512Mi"
    requests:
      memory: "384Mi"
  secretKey: django-insecure-abcdefghijklmnopqrstuvwxyz0123456789!"£$%^&*()"
  terminationGracePeriodSeconds: 20

proxy:
  image:
    repository: ghcr.io/m5lapp/fitness-tracker-proxy
    tag: ""
  ports:
    internal: 8080
  replicas: 1
  resources:
    limits:
      cpu: "200m"
      memory: "64Mi"
    requests:
      cpu: "200m"
      memory: "64Mi"

ingress:
  active: true
  clusterIssuer: letsencrypt-prod
  domain: example.com
  fqdn: fitness-tracker.example.com
  mtls:
    active: false
    clientCert:
      duration: 8760h # 1 year.
      userName: fitness-tracker
    trustNamespace: cert-manager
    rootCA:
      certificateSecret: example-com-root-ca-cert
      issuer: example-com-root-ca-issuer
  tls:
    secretName: fitness-tracker-tls-prod

serviceMesh:
  linkerd:
    active: false

dbBackup:
  active: false
  schedule: "0 2 * * *"
  resources:
    limits:
      cpu: "128m"
      memory: "32Mi"
  retentionDays: "120"
  volume:
    capacity: 100Mi
    storageClass: longhorn

