{{ if and .Values.dbBackup.active (eq .Values.app.database.engine "postgresql") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-database-backups
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dbBackup.volume.capacity }}
  storageClassName: {{ .Values.dbBackup.volume.storageClass }}

---

{{ $dbMTLS := and .Values.app.database.mtls.cert .Values.app.database.mtls.key -}}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup-data
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.dbBackup.schedule}}
  jobTemplate:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: database
        technology: postgres
        job: database-backup-data
    spec:
      template:
        spec:
          containers:
          - name: database-backup-data
            image: docker.io/postgres:18-alpine
            command:
            - /bin/sh
            args:
            - -c
            - |
              ls -l /var/lib/postgresql/backups/ && \
              pg_dump "
                        {{- range $k, $v := (fromJson .Values.app.database.options) }}
                          {{ $k }}='{{ $v }}'
                        {{- end }}
                        {{- with .Values.app.database.mtls.keyPassword }}
                          sslpassword='{{ . }}'
                        {{- end }}
                      " \
                      > /var/lib/postgresql/backups/$(date +"%Y%m%d%H%M%S").sql && \
              echo "Removing backups older than ${BACKUP_RETENTION_DAYS} days" && \
              find /var/lib/postgresql/backups/ \
                   -type f \
                   -name "*.sql" \
                   -mtime +${BACKUP_RETENTION_DAYS} \
                   -delete && \
              ls -l /var/lib/postgresql/backups/
            env:
            - name: BACKUP_RETENTION_DAYS
              value: {{ quote .Values.dbBackup.retentionDays }}
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: FT_DB_HOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: FT_DB_PORT
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: FT_DB_NAME
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: FT_DB_USERNAME
            {{- if .Values.app.database.password }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: FT_DB_PASSWORD
            {{- end }}
            {{- if .Values.app.database.sslmode }}
            - name: PGSSLMODE
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: FT_DB_SSLMODE
            {{- end }}
            {{- if $dbMTLS }}
            - name: PGSSLCERT
              value: /tmp/mtls/tls.crt
            - name: PGSSLKEY
              value: /tmp/mtls/tls.key
            {{- with .Values.app.database.mtls.caCert}}
            - name: PGSSLROOTCERT
              value: /tmp/mtls/ca.crt
            {{- end }}
            {{- end }}
            {{- with .Values.app.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: database-backups
              mountPath: /var/lib/postgresql/backups/
            {{- if $dbMTLS }}
            - name: {{ .Chart.Name }}-db-mtls-certs
              mountPath: /tmp/mtls/
              readOnly: true
            {{- end }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Chart.Name }}
          volumes:
          - name: database-backups
            persistentVolumeClaim:
              claimName: {{ .Chart.Name }}-database-backups
          {{- if $dbMTLS }}
          - name: {{ .Chart.Name }}-db-mtls-certs
            secret:
              secretName: {{ .Chart.Name }}-db-mtls-certs
              defaultMode: 0400
          {{- end }}
{{- end }}

# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: database-backup-data-debug
#   namespace: fitness-tracker
#   labels:
#     app: fitness-tracker
#     component: database
#     technology: postgres
#     job: database-backup-data
# spec:
#   containers:
#   - name: database-backup-data-debug
#     image: docker.io/postgres:14-alpine
#     command:
#     - sleep
#     args:
#     - "3600"
#     resources:
#       limits:
#         cpu: "128m"
#         memory: "32Mi"
#     volumeMounts:
#     - name: database-backups
#       mountPath: /var/lib/postgresql/backups/
#   restartPolicy: Never
#   serviceAccountName: fitness-tracker
#   volumes:
#   - name: database-backups
#     persistentVolumeClaim:
#       claimName: ft-database-backups
