apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-proxy
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    component: proxy
  ports:
  - port: {{ .Values.proxy.ports.internal }}
    targetPort: {{ .Values.proxy.ports.internal }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-proxy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: proxy
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: proxy
        technology: nginx
    spec:
      containers:
      - name: {{ .Chart.Name }}-proxy
        image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.proxy.ports.internal }}
        {{- with .Values.proxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: {{ .Chart.Name }}
